# Generated by Django 4.2.30 on 2026-05-19 11:40

from django.db import migrations, models
import project.grooming.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discord_user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(default=project.grooming.models._empty_session_payload)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('lead_id', models.CharField(db_index=True, max_length=64)),
                ('discord_user_id', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField()),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discord_user_id', models.CharField(db_index=True, max_length=64)),
                ('user_message', models.TextField(blank=True, default='')),
                ('bot_reply', models.TextField(blank=True, default='')),
                ('intent', models.CharField(blank=True, default='', max_length=32)),
                ('stage_before', models.CharField(blank=True, default='', max_length=32)),
                ('stage_after', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
